### ISSUE TITLE
patch_LEDE.sh

### ISSUE THREAD

**Issue by rule2c** [gwlim/mips74k-lede-patch#15]
Applying patch 012-update-kernel-version.patch
patching file include/kernel-version.mk
Hunk #1 FAILED at 3.
1 out of 1 hunk FAILED -- saving rejects to file include/kernel-version.mk.rej

How to reslove?please

**Comment by gwlim** [comment]
Fixed with https://github.com/gwlim/mips74k-ar71xx-lede-patch/commit/aea2b69af8c5e165cef405753fc88071a794c17a

**Comment by protocold** [comment]
The problem came back, I checked the file:

osboxes@osboxes:~/MW4530R/lede$ cat include/kernel-version.mk
# Use the default kernel version if the Makefile doesn't override it

LINUX_RELEASE?=1

LINUX_VERSION-3.18 = .43
LINUX_VERSION-4.4 = .93

LINUX_KERNEL_HASH-3.18.43 = 1236e8123a6ce537d5029232560966feed054ae31776fe8481dd7d18cdd5492c
LINUX_KERNEL_HASH-4.4.93 = ed349314f16e78a6571b5f8884f6452782aef6c26b81bcc7ccdac44ecd917c36

ifdef KERNEL_PATCHVER
  LINUX_VERSION:=$(KERNEL_PATCHVER)$(strip $(LINUX_VERSION-$(KERNEL_PATCHVER)))
endif

split_version=$(subst ., ,$(1))
merge_version=$(subst $(space),.,$(1))
KERNEL_BASE=$(firstword $(subst -, ,$(LINUX_VERSION)))
KERNEL=$(call merge_version,$(wordlist 1,2,$(call split_version,$(KERNEL_BASE))))
KERNEL_PATCHVER ?= $(KERNEL)

# disable the md5sum check for unknown kernel versions
LINUX_KERNEL_HASH:=$(LINUX_KERNEL_HASH-$(strip $(LINUX_VERSION)))
LINUX_KERNEL_HASH?=x

I guess it needs another update??!
